repos:
  - repo: local
    hooks:
      - id: yamlfmt
        name: Format YAML files
        entry: yamlfmt .
        language: system
        files: \.(yaml|yml)$
      - id: tombi
        name: Format TOML files
        entry: tombi format
        language: system
        files: \.(toml)$
      - id: mdformat
        name: Format Markdown files
        entry: uv run mdformat
        language: system
        files: \.(md)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
